Newsweek clone feature branch
mosesmuchemi/newsweek-clone pull request #1
Opened 2019-11-12 10:30 UTC by mosesmuchemi

Creating a Pull request for peer to peer code review, stickler and TSE review

2019-11-13 17:04 UTC, shloch commented
### Pull request under review by SHEY LOUIS

2019-11-13 18:08 UTC, shloch commented
Great Job @mosesmuchemi  👏 👏 
Design looks good, adapts very well to the breakpoints and mimics the original pretty well at many levels (but not all). I require you to bring minor changes though :

**CHANGES REQUIRED:**
1-  There're validation errors (please validate your html syntax and semantics here -> `https://validator.w3.org/nu/#textarea` )

2 - Try to mimic Better this Header design

original image at break points around 900px (date disappears, and 'NEWSWEEK' moves to right)
![Screen Shot 2019-11-13 at 6 33 56 PM](https://user-images.githubusercontent.com/40712459/68788080-02eec780-0643-11ea-8179-a5003ec2f571.png)

Your own image
![Screen Shot 2019-11-13 at 6 34 04 PM](https://user-images.githubusercontent.com/40712459/68788133-2580e080-0643-11ea-953c-2dd128ef70ee.png)

I know you you did it at a lower breakpoint (around 700px)

3 - "MORE STORIES" SECTION

original website  (notice the background color):
![Screen Shot 2019-11-13 at 6 46 12 PM](https://user-images.githubusercontent.com/40712459/68788850-86f57f00-0644-11ea-934f-7aa76644b639.png)

Your own display
![Screen Shot 2019-11-13 at 6 46 29 PM](https://user-images.githubusercontent.com/40712459/68788950-b1473c80-0644-11ea-8810-fd1ef5b90da6.png)

4 - "IN THE MAGAZINE" SECTION

original website: (notice the RED-color titles under the images)
![Screen Shot 2019-11-13 at 6 48 27 PM](https://user-images.githubusercontent.com/40712459/68789015-d50a8280-0644-11ea-8861-6d12f0af2c8f.png)


Your own version
![Screen Shot 2019-11-13 at 6 48 36 PM](https://user-images.githubusercontent.com/40712459/68789163-3599bf80-0645-11ea-9913-13863bfe4c09.png)

5 - 'FEATURED SLIDESHOWS' section

original version (notice the spaces/padding/gutters around the block)
![Screen Shot 2019-11-13 at 6 53 27 PM](https://user-images.githubusercontent.com/40712459/68789370-9e813780-0645-11ea-96c4-ee3f0e620b83.png)

your own version (yours doesn't have the gutter at an important breakpoint around 1100px )
![Screen Shot 2019-11-13 at 6 53 35 PM](https://user-images.githubusercontent.com/40712459/68789388-a7720900-0645-11ea-8dac-60e940bad4e5.png)

Monitor and correct these spaces on other sections as well, you will notice more

6 - FOOTER SECTION

original version  (notice the links below "NEWSWEEK" take up about 50% of the page, horizontally)
![Screen Shot 2019-11-13 at 6 58 43 PM](https://user-images.githubusercontent.com/40712459/68789716-48f95a80-0646-11ea-9096-7d080667dd05.png)

your own version (yours is about 25-30%)
![Screen Shot 2019-11-13 at 6 59 01 PM](https://user-images.githubusercontent.com/40712459/68789798-6cbca080-0646-11ea-8f71-54dd9d6dbdd9.png)

7 - Error display on small screens

original version :  (notice at small screens, TOP STORIES passes to the top )
![Screen Shot 2019-11-13 at 7 06 24 PM](https://user-images.githubusercontent.com/40712459/68790325-611da980-0647-11ea-8b65-bdeb346b4a6c.png)

Your own version :

You have but "FEATURED STORIES"
![Screen Shot 2019-11-13 at 7 06 34 PM](https://user-images.githubusercontent.com/40712459/68790558-cd98a880-0647-11ea-93bf-571ea2d9ad2e.png)

And your "TOP STORIES" is pushed down and doesn't display properly 
![Screen Shot 2019-11-13 at 7 10 36 PM](https://user-images.githubusercontent.com/40712459/68790628-e99c4a00-0647-11ea-9f20-92553e408acb.png)

Some  sections are even cut (still on the "TOP STORIES" section), please take a look at this very well 
![Screen Shot 2019-11-13 at 7 11 28 PM](https://user-images.githubusercontent.com/40712459/68790699-0e90bd00-0648-11ea-991c-a09043d94450.png)

It long project, it's impressive what you have brought up so far.

I am also impressed at your style of reproducing this design with very limited/absence of media queries. Some of the issues above will be solved with media queries.

Please bring the changes above and re-submit review form

2019-11-14 22:44 UTC, mosesmuchemi commented
refactored to put in the changes recommended by TSE

2019-11-14 22:49 UTC, Anna-Myzukina commented
### Pull Request under the review by Anna Muzykina (TSE)

2019-11-14 23:30 UTC, Anna-Myzukina commented
## Hi Muchemi! ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Your project looks :+1:  and very discriptive readme file!
#### But need some Required Changes

## [OPTIONAL]
##### Footer

* [x] It contains Newsweek logo.
* [ ] It contains social media icons.
* [x] It contains main navigation links.
* [x] **It changes with RWD breakpoints.**

In "TOP STORY" section little error let`s fix it
*** you use col-5 ***
![before-sm](https://user-images.githubusercontent.com/26605804/68904567-e6d44e80-0746-11ea-917f-db22f15186d7.png)

*** if you use col-sm enstead of col-5 ***
![after-sm](https://user-images.githubusercontent.com/26605804/68904575-ed62c600-0746-11ea-9865-83ca488eea62.png)


### Make changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*
*Happy coding *

2019-11-14 23:35 UTC, Anna-Myzukina commented on index.html
> +            <div class="col-5 col-md-7 col-lg-5 top-story-col">
Better to use col-sm instead of col-5 ( line 129)

2019-11-14 23:39 UTC, Anna-Myzukina requested changes
Not displayed social media icons in the footer

2019-11-18 14:20 UTC, mosesmuchemi commented
done corrections as suggested by second TSE reviewer

2019-11-18 17:20 UTC, suretrust requested changes
Hi @mosesmuchemi,

### Great job thus far, :raised_hands: just one more suggestion to wrap it up. Please see my comments on your code.

**Kindly submit for another code review once these issues have been fixed.** _Happy coding!_ :tada:

2019-11-18 17:20 UTC, suretrust commented on index.html
> +        </div>
The width of the navbar on all screens is inaccurate. Please see the images below:

**Yours**
![navbar](https://user-images.githubusercontent.com/31304943/69074013-d5cd5b00-0a2e-11ea-8705-f13ddb3559d6.png)
![navbar2](https://user-images.githubusercontent.com/31304943/69074015-d5cd5b00-0a2e-11ea-87fa-0695ab5bd97b.png)
![navbar3](https://user-images.githubusercontent.com/31304943/69074016-d665f180-0a2e-11ea-9078-0838084b9568.png)

**Original**
![nav-def](https://user-images.githubusercontent.com/31304943/69074256-4aa09500-0a2f-11ea-86a0-b846c393591a.png)
![nav-def-2](https://user-images.githubusercontent.com/31304943/69074258-4b392b80-0a2f-11ea-9b6a-210ce3ada5e9.png)
![nav-def-3](https://user-images.githubusercontent.com/31304943/69074260-4b392b80-0a2f-11ea-8aef-535ccc25409a.png)

2019-11-18 17:20 UTC, suretrust commented on index.html
> +        </div>
The navigation links/buttons alignments are also inaccurate on a medium screen.

2019-12-04 08:34 UTC, Oluwadamilareolusakin commented
# Fantastic job @mosesmuchemi :rocket: 
Remember to keep this energy going throughout the program, you'll be awesome for it :smile: 

#### Please merge this beautifully done job and move on with your projects!

2019-12-04 08:34 UTC, nikasulo approved these changes

2019-12-04 08:49 UTC, merged